"""Export a build to something Minecraft can load, and write a README beside it.

    python3 tools/build_world.py                 # the Mk III machine
    python3 tools/build_world.py --what console  # the Mk II decimal console
    python3 tools/build_world.py --what alu --width 8

Produces, under out/build/<name>/:

    structures/   .nbt files for structure blocks, plus a manifest
    datapack/     a datapack whose build function places the whole thing
    README.md     what the files are and how to use them
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from rscalc import mcbuild
from rscalc.engine import World
from rscalc.pla import compile_netlist

OUT = os.path.join(os.path.dirname(__file__), "..", "out", "build")

README = """# {name}

A calculator made of Minecraft redstone, generated by the compiler in this
repository and verified in a tick-accurate simulator before export.

* **{blocks:,} blocks**, {dx} x {dy} x {dz} (X x Y x Z)
* Repeaters are set to **{delay}**, which is the setting this build is verified
  stable at. Lower settings are faster and burn torches out — see DESIGN §13.
* Targets Java Edition data version {dv} — a newer world upgrades it on load.
* Solid blocks are `{solid}`; change `--solid` to build it out of something else.
* It grows **+X, +Y, +Z** from where you stand, so start at or below **Y={maxy}**
  — above that it runs out of world at Y=319.
* `/function` needs permission level 2. In single player that means cheats on.

## Option 1 — the datapack (no mods, no structure blocks)

1. Copy `datapack/` into your world's `datapacks/` folder, as its own folder.
2. `/reload`
3. Stand where you want the **minimum corner** of the build (it grows +X, +Y, +Z
   from you) and run:

   ```
   {entry}
   ```

It runs {commands:,} commands, **one batch per game tick over {ticks} ticks**
(about {seconds:.1f} seconds). It is paced rather than run in one go for two
reasons: a single tick holding all of it freezes the server, and dropping half a
million redstone blocks into the world in the same instant is the worst possible
starting transient for a machine this deep — see DESIGN §13 for what coincident
transitions do to torches.

Placement follows a marker entity summoned where you ran the command, because a
`schedule`d function forgets where it was called from and would otherwise build
the machine at world origin.

### It will not run unless you force-load it — **read this one**

Redstone only ticks in chunks the game is *simulating*. This build is
{chunks} chunks. At Java's default simulation distance of 10 a player holds a
21 x 21 square — 441 chunks, about a fifth of it — so you can stand at the
control wall, throw a lever, and the far end of the machine simply never moves.
Nothing errors. The answer just never arrives.

`{load}` covers the whole footprint with {forceload_commands} `/forceload`
commands (one command takes at most 256 chunks). `build` runs it for you before
placing anything. `{unload}` releases them again.

Force-loading {chunks} chunks is not free — that is a permanent load on the
server for as long as it is set.

### Taking it back out

```
{clear}
```

from the same corner. It clears one Y layer per tick over {clear_ticks} ticks.

## Option 2 — structure files

Copy `structures/*.nbt` into `<world>/generated/minecraft/structures/`, then for
each entry in `structures/{name}_manifest.json` place a structure block, load
the named structure, and set its position to the `offset` given. Structure
blocks are limited to 48 blocks a side, which is why there are {pieces} of them.

{controls}## Before you build it

This machine is far larger than a Minecraft server ticks comfortably — it is a
simulation artefact first and an in-game build second. Build it in a creative
flat world, and expect the answer to take {settle} game ticks ({secs:.0f}
seconds) to appear.

## Orientation conventions

These are flipped on the way out of the simulator, and getting them wrong fails
silently — the build looks perfect and computes nothing:

* a repeater's and comparator's `facing` in Minecraft points from the **output**
  side to the **input** side, the opposite of this simulator's;
* a wall torch's `facing` points **away** from its support.
"""


#: Each target's verified repeater setting. Not a taste: the machine burns 117
#: torches out at 2 and survives only gentle sequences at 3, and exporting a
#: build at a setting nothing has been tested at is how you ship a world that
#: looks right and computes nonsense.
VERIFIED_DELAY = {"machine": None, "console": 2, "alu": 2}


def pack_name(width):
    """The Mk III's export name, which `mcbuild` lowercases into its namespace.

    Written once because two places need it: this tool, which exports the pack,
    and `tools/build_preview.py`, which tells the page what namespace to put in
    the pack *it* generates in the browser. The page used to compose its own
    (`machine_mk3`), so a reader following the site's instructions typed a
    `/function` the downloaded pack did not answer to.
    """
    return f"rscalc_mk3_{width}bit"


def target(what, width, delay):
    if what == "machine":
        from rscalc.machine import build_machine, SETTLE_GT
        m = build_machine(width=width or 10, repeater_delay=delay)
        return pack_name(m.width), m.world, dict(
            m.stats, settle=SETTLE_GT, controls=controls_note(m))
    if what == "console":
        from rscalc.console import build_console
        nl, w, L, pads, lamps, stats, ready = build_console(repeater_delay=delay)
        return "rscalc_console", w, stats
    if what == "alu":
        from rscalc.alu import build_alu
        nl = build_alu(width=width or 8, carry="cla")
        w = World()
        compile_netlist(nl, w, repeater_delay=delay)
        return f"rscalc_alu_{width or 8}bit", w, {
            "gates": nl.gate_count(), "depth": nl.depth()}
    raise SystemExit(f"unknown target {what!r}")


def controls_note(m):
    """Where the player's controls are, relative to the build's minimum corner.

    Every coordinate in the datapack is an offset from where you stand when you
    run it, so these are the numbers you actually need to find the panel in a
    600,000-block build.
    """
    from rscalc.alu import OPS
    from rscalc.panel import WALK_X
    (x0, y0, z0), _ = m.world.bounds()

    def rel(p):
        return (p[0] - x0, p[1] - y0, p[2] - z0)

    levers = list(m.levers.values()) + list(m.keys.values())
    rs = [rel(p) for p in levers]
    walk = rel((WALK_X[0], min(p[1] for p in levers) - 1,
                min(p[2] for p in levers)))
    rows = sorted({p[1] for p in rs})
    kz = sorted({p[2] for p in [rel(m.keys[k]) for k in sorted(m.keys)]})
    optable = "".join(
        f"| z = {z} | {OPS[2 * c]} | {OPS[2 * c + 1]} |\n"
        for c, z in enumerate(kz))

    return """## Where the controls are

All 28 controls are on one wall at **x = {x}**, relative to the minimum corner,
in fourteen columns two blocks apart spanning **z = {z0}..{z1}**. Each column
holds two levers, the upper at **y = {yhi}** and the lower at **y = {ylo}**:

| columns | upper lever | lower lever |
|---|---|---|
{optable}| z = {b0} + 2i, for bit i = 0..9 | A bit i | B bit i |

The glass walkway is at **y = {yw}**, x = {xw} and {xw2}: stand on it and your
feet are level with the lower row while the upper row is a 2.6-block reach, so
the whole wall is workable without moving more than a few steps.

Flip the operand levers, then flip an operation lever on and off again the way
you would press a button — the keypad latches on the way down and holds the
choice after you let go.

**One operation lever at a time.** The keypad is one-hot and it answers two
keys held down honestly rather than refusing: both latch, and the opcode
becomes their OR. Leave SHL on and flip ADD and the machine computes SHL,
correctly and without complaint. They are on the wall in front of you, so a
glance along the row is the check.

The answer appears on the lamp digits at the far end of the build; it is a long
walk, and that is the one part of using this thing that is still bad.

""".format(optable=optable, x=rs[0][0], z0=min(p[2] for p in rs), z1=max(p[2] for p in rs),
           k1=min(p[2] for p in rs) + 2, k2=min(p[2] for p in rs) + 4,
           k3=min(p[2] for p in rs) + 6, b0=min(p[2] for p in rs) + 8,
           yhi=rows[-1], ylo=rows[0],
           yw=walk[1], xw=walk[0], xw2=walk[0] + 1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--what", default="machine",
                    choices=["machine", "console", "alu"])
    ap.add_argument("--width", type=int, default=None)
    ap.add_argument("--delay", type=int, default=None,
                    help="repeater setting; defaults to the verified one")
    ap.add_argument("--solid", default=mcbuild.DEFAULT_SOLID)
    ap.add_argument("--settle", type=int, default=0,
                    help="worst-case settle in game ticks, for the README")
    args = ap.parse_args()

    if args.delay is None:
        from rscalc.machine import DEFAULT_DELAY
        args.delay = VERIFIED_DELAY[args.what] or DEFAULT_DELAY

    t0 = time.time()
    name, world, stats = target(args.what, args.width, args.delay)
    problems = world.lint()
    if problems:
        raise SystemExit(f"refusing to export a world with {len(problems)} "
                         f"lint problems: {problems[:3]}")
    (x0, y0, z0), (x1, y1, z1) = world.bounds()
    root = os.path.abspath(os.path.join(OUT, name))
    os.makedirs(root, exist_ok=True)

    man = mcbuild.export_structures(world, os.path.join(root, "structures"),
                                    name=name, solid=args.solid)
    pack = mcbuild.export_datapack(world, os.path.join(root, "datapack"),
                                   name=name, solid=args.solid)

    with open(os.path.join(root, "README.md"), "w") as f:
        f.write(README.format(
            name=name, blocks=len(world.blocks),
            dx=x1 - x0 + 1, dy=y1 - y0 + 1, dz=z1 - z0 + 1,
            dv=mcbuild.DATA_VERSION, solid=args.solid,
            entry="/" + pack["entry"], commands=pack["commands"],
            files=pack["files"], pieces=len(man["pieces"]),
            clear="/" + pack["clear"], ticks=pack["ticks"],
            load="/" + pack["load"], unload="/" + pack["unload"],
            chunks=f"{pack['chunks']:,}",
            forceload_commands=pack["forceload_commands"],
            maxy=319 - (y1 - y0),
            clear_ticks=pack["clear_ticks"], seconds=pack["ticks"] / 20,
            delay=args.delay,
            controls=stats.get("controls", ""),
            settle=args.settle or stats.get("settle", 0),
            secs=(args.settle or stats.get("settle", 0)) / 20))

    size = sum(os.path.getsize(os.path.join(dp, f))
               for dp, _, fs in os.walk(root) for f in fs)
    print(f"{name}: {len(world.blocks):,} blocks, "
          f"{x1-x0+1}x{y1-y0+1}x{z1-z0+1}")
    print(f"  structures: {len(man['pieces'])} .nbt chunks")
    print(f"  datapack:   {pack['commands']:,} commands in {pack['files']} "
          f"functions ({len(world.blocks)/max(1,pack['commands']):.1f} blocks "
          f"per command)")
    print(f"  total {size/1024/1024:.1f} MB in {root} ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
