"""Export a build to something Minecraft can load, and write a README beside it.

    python3 tools/build_world.py                 # the Mk III machine
    python3 tools/build_world.py --what console  # the Mk II decimal console
    python3 tools/build_world.py --what alu --width 8

Produces, under out/build/<name>/:

    structures/   .nbt files for structure blocks, plus a manifest
    datapack/     a datapack whose build function places the whole thing
    README.md     what the files are and how to use them
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from rscalc import mcbuild
from rscalc.engine import World
from rscalc.pla import compile_netlist

OUT = os.path.join(os.path.dirname(__file__), "..", "out", "build")

README = """# {name}

A calculator made of Minecraft redstone, generated by the compiler in this
repository and verified in a tick-accurate simulator before export.

* **{blocks:,} blocks**, {dx} x {dy} x {dz} (X x Y x Z)
* Targets Java Edition data version {dv} — a newer world upgrades it on load.
* Solid blocks are `{solid}`; change `--solid` to build it out of something else.

## Option 1 — the datapack (no mods, no structure blocks)

1. Copy `datapack/` into your world's `datapacks/` folder, as its own folder.
2. `/reload`
3. Stand where you want the **minimum corner** of the build (it grows +X, +Y, +Z
   from you) and run:

   ```
   {entry}
   ```

It runs {commands:,} commands in {files} batches. Give it a moment.

## Option 2 — structure files

Copy `structures/*.nbt` into `<world>/generated/minecraft/structures/`, then for
each entry in `structures/{name}_manifest.json` place a structure block, load
the named structure, and set its position to the `offset` given. Structure
blocks are limited to 48 blocks a side, which is why there are {pieces} of them.

## Before you build it

This machine is far larger than a Minecraft server ticks comfortably — it is a
simulation artefact first and an in-game build second. Build it in a creative
flat world, and expect the answer to take {settle} game ticks ({secs:.0f}
seconds) to appear.

## Orientation conventions

These are flipped on the way out of the simulator, and getting them wrong fails
silently — the build looks perfect and computes nothing:

* a repeater's and comparator's `facing` in Minecraft points from the **output**
  side to the **input** side, the opposite of this simulator's;
* a wall torch's `facing` points **away** from its support.
"""


def target(what, width, delay):
    if what == "machine":
        from rscalc.machine import build_machine
        m = build_machine(width=width or 10, repeater_delay=delay)
        return f"rscalc_mk3_{m.width}bit", m.world, m.stats
    if what == "console":
        from rscalc.console import build_console
        nl, w, L, pads, lamps, stats, ready = build_console(repeater_delay=delay)
        return "rscalc_console", w, stats
    if what == "alu":
        from rscalc.alu import build_alu
        nl = build_alu(width=width or 8, carry="cla")
        w = World()
        compile_netlist(nl, w, repeater_delay=delay)
        return f"rscalc_alu_{width or 8}bit", w, {
            "gates": nl.gate_count(), "depth": nl.depth()}
    raise SystemExit(f"unknown target {what!r}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--what", default="machine",
                    choices=["machine", "console", "alu"])
    ap.add_argument("--width", type=int, default=None)
    ap.add_argument("--delay", type=int, default=3)
    ap.add_argument("--solid", default=mcbuild.DEFAULT_SOLID)
    ap.add_argument("--settle", type=int, default=0,
                    help="worst-case settle in game ticks, for the README")
    args = ap.parse_args()

    t0 = time.time()
    name, world, stats = target(args.what, args.width, args.delay)
    problems = world.lint()
    if problems:
        raise SystemExit(f"refusing to export a world with {len(problems)} "
                         f"lint problems: {problems[:3]}")
    (x0, y0, z0), (x1, y1, z1) = world.bounds()
    root = os.path.abspath(os.path.join(OUT, name))
    os.makedirs(root, exist_ok=True)

    man = mcbuild.export_structures(world, os.path.join(root, "structures"),
                                    name=name, solid=args.solid)
    pack = mcbuild.export_datapack(world, os.path.join(root, "datapack"),
                                   name=name, solid=args.solid)

    with open(os.path.join(root, "README.md"), "w") as f:
        f.write(README.format(
            name=name, blocks=len(world.blocks),
            dx=x1 - x0 + 1, dy=y1 - y0 + 1, dz=z1 - z0 + 1,
            dv=mcbuild.DATA_VERSION, solid=args.solid,
            entry="/" + pack["entry"], commands=pack["commands"],
            files=pack["files"], pieces=len(man["pieces"]),
            settle=args.settle or 0, secs=(args.settle or 0) / 20))

    size = sum(os.path.getsize(os.path.join(dp, f))
               for dp, _, fs in os.walk(root) for f in fs)
    print(f"{name}: {len(world.blocks):,} blocks, "
          f"{x1-x0+1}x{y1-y0+1}x{z1-z0+1}")
    print(f"  structures: {len(man['pieces'])} .nbt chunks")
    print(f"  datapack:   {pack['commands']:,} commands in {pack['files']} "
          f"functions ({len(world.blocks)/max(1,pack['commands']):.1f} blocks "
          f"per command)")
    print(f"  total {size/1024/1024:.1f} MB in {root} ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
